### ISSUE TITLE
How to train on Eigen Split dataset containing 39810 training KITTI images?

### ISSUE THREAD

**Issue by aditbhrgv** [yearning-zenith/supervised_dispnet#6]
Hi,

I used the data/prepare_train_data.py script but it generates random number of train and test images for KITTI raw dataset.
See logs below:

=> fetching scenes in '/home/projects/kitti_supervised_formatted'
29530 samples found in 56 train scenes
14692 samples found in 8 valid scenes

I want to train on Eigen split of train and test images. 

Command used to prepare train data:
python data/prepare_train_data.py  /media/adit/New\ Volume1/Downloads/kitti_data_raw --dataset-format 'kitti'  --width 416 --height 128 --num-threads 8  --static-frames data/static_frames.txt --with-depth --with-pose --dump-root  /home/projects/kitti_supervised_formatted
Retrieving frames
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 33/33 [12:58<00:00, 23.59s/it]
Generating train val lists
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 32/32 [00:00<00:00, 1147.61it/s]

How can I prepare my data for the same?

Thanks

**Comment by zenithfang** [comment]
I think you need to setup random seed if you want to keep it all the same on same machine. Usually, we only make up dataset once and continue to use it.
