### ISSUE TITLE
关于vgg和resnet对比的疑问

### ISSUE THREAD

**Issue by cnexah** [yearning-zenith/supervised_dispnet#7]
您好！想请教一个问题：
在您的论文Table 1中， vgg16要优于resnet。但是在DORN的论文Table1中，resnet要优于vgg16。
请问是什么导致了不同的结论？
非常感谢！！

**Comment by zenithfang** [comment]
我的实验里面vgg和resnet-50差不多，dorn的table 1的设定我不记得了，如果差别很小的话，不同的random seed和训练时长都会导至结果细微变化

**Comment by cnexah** [comment]
非常感谢！
